/* [Grok-Bot] V1.54: Sri Hanuman Chalisa als neuer Prayer. Text und Akkorde aus dem Prathana-Heft (Sri Vitthal Dham, S. 21-23), Ton: Hanuman Chalisa (prabhu) 11 aus Telegram (BM Prayers - Waves of love), abgelegt in Dropbox 05 Prayers. Uebersetzung sinngemaess. */
(function(){
  var audio = "https://www.dropbox.com/scl/fo/9jrivp0fkl4bfo9t0dejx/AIhKtbXquRNBdUPTntYvPTg/Hanuman%20Chalisa%20(prabhu)%2011.mp3?rlkey=s8lox2d2652b2i133h1jjty3k&dl=1";
  var C4 = "D     C     G     D";
  function v(n, ch, sa, ue, en){ return { nr:String(n), ch:ch, sa:sa, ue:ue, en:en }; }
  /* V1.54: Govinda-MP3 mit dem richtigen Datei-Schluessel im Dropbox-Ordner, vorher lud sie nicht */
  var gv = PRAYERS.find(function(p){ return p.id==="govinda"; });
  if(gv) gv.audio = "https://www.dropbox.com/scl/fo/9jrivp0fkl4bfo9t0dejx/AAHyM8CgbCWzOJ-fFLJTP80/Govinda%20Prayer%20(prabhu)%203.mp3?rlkey=s8lox2d2652b2i133h1jjty3k&dl=1";
  PRAYERS.push({
    id: "hanuman",
    titel: "Śrī Hanumān Cālīsā",
    autor: "Tulasīdāsa · Bhakti Marga Prayers",
    audio: audio,
    preferFile: true,
    quelle: "Prathana with chords · Sri Vitthal Dham · S. 21–23 · Ton: Hanuman Chalisa (prabhu) 11 (Telegram, BM Prayers)",
    hinweis: "Text und Akkorde wie im Heft, vier Zeilen je Strophe. Ton von den Prabhus. Übersetzung sinngemäß.",
    hinweisDe: "Text und Akkorde wie im Heft, vier Zeilen je Strophe. Ton von den Prabhus. Übersetzung sinngemäß.",
    hinweisEn: "Lyrics and chords as in the booklet, four lines per verse. Recording by the Prabhus. Translation approximate.",
    zeilen: [
      v("Dohā 1", C4, "śrī guru caraṇa saroja raja\nnija manu mukura sudhāri\nbaranaūṁ raghuvara vimala jasu\njo dāyaka phala cāri",
        "Mit dem Staub der Lotusfüße des Gurus reinige ich den Spiegel meines Geistes. Dann besinge ich den reinen Ruhm Ramas, der die vier Früchte des Lebens schenkt.",
        "With the dust of the Guru's lotus feet I cleanse the mirror of my mind. Then I sing the pure glory of Rama, who grants the four fruits of life."),
      v("Dohā 2", C4, "buddhi hīna tanu jāni-ke\nsumirauṁ pavana kumara\nbala buddhi vidyā dehu mohi\nharahu kaleśa vikāra",
        "Ich weiß, wie wenig Verstand ich habe, und denke an dich, Sohn des Windes. Gib mir Kraft, Einsicht und Wissen, nimm Kummer und Unreinheit von mir.",
        "Knowing how little understanding I have, I remember you, son of the wind. Give me strength, wisdom and knowledge, and remove my sorrows and flaws."),
      v("Refrain", "D     C     G     D", "siyā vara rāmacandra pada jai śaraṇam\nrāmaji se rāma rāma kahiyo kahiyo-ji hanumāna-ji",
        "Zuflucht zu den Füßen Ramachandras, des Gemahls von Sita. Hanuman, sag Rama unser „Rama, Rama“.",
        "Refuge at the feet of Ramachandra, Sita's beloved. Hanuman, carry our \"Rama, Rama\" to Rama."),
      v("1", C4, "jaya hanumān jñāna guna sāgara\njaya kapīsa tihum̐ loka ujāgara\nrāma dūta atulita bala dhāmā\nañjani putra pavana suta nāmā",
        "Sieg dir, Hanuman, Ozean von Wissen und Tugend, Herr der Affen, der die drei Welten erhellt. Du bist Ramas Bote voll unvergleichlicher Kraft, Sohn der Anjani, genannt Sohn des Windes.",
        "Victory to Hanuman, ocean of wisdom and virtue, lord of the monkeys who lights up the three worlds. Rama's messenger of matchless strength, son of Anjani, called son of the wind."),
      v("2", C4, "mahāvīra vikrama bajaraṅgī\nkumati nivāra sumati ke saṅgī\nkañcana varana virāja subesā\nkānhana kuṇḍala kuñcita kesā",
        "Großer Held, mutig, mit diamantenem Körper. Du vertreibst schlechte Gedanken und begleitest die guten. Goldfarben, schön gekleidet, mit Ohrringen und lockigem Haar.",
        "Great hero, valiant, with a body like a thunderbolt. You dispel evil thoughts and keep company with the good. Golden in color, finely dressed, with earrings and curly hair."),
      v("3", C4, "hātha vajra aura dvajā birājai\nkāndhe mūñja janeu sājai\nśankara suvana kesarī nandana\nteja pratāpa mahā jaga vandana",
        "In deinen Händen leuchten Donnerkeil und Banner, über der Schulter die heilige Schnur. Du Sohn Shivas und Freude Kesaris, dein Glanz wird von der ganzen Welt verehrt.",
        "Thunderbolt and banner shine in your hands, the sacred thread across your shoulder. Born of Shiva, joy of Kesari, your radiance is honored by the whole world."),
      v("4", C4, "vidyāvāna gunī ati cātura\nrāma kāja karibe ko ātura\nprabhu caritra sunibe ko rasiyā\nrāma lakhana sītā mana basiyā",
        "Gelehrt, tugendhaft und sehr klug, immer bereit, Ramas Werk zu tun. Du liebst es, die Geschichten des Herrn zu hören. Rama, Lakshmana und Sita wohnen in deinem Herzen.",
        "Learned, virtuous and very wise, always eager to do Rama's work. You delight in hearing the Lord's stories. Rama, Lakshmana and Sita dwell in your heart."),
      v("5", C4, "sūkṣma rūpa dhari siyahiṁ dikhāvā\nvikaṭa rūpa dhari laṅka jarāvā\nbhīma rūpa dhari asura saṁ(g)hāre\nrāma-candra ke kāja saṁvāre",
        "Winzig klein zeigtest du dich Sita, riesig und furchtbar brannte deine Gestalt Lanka nieder. Mächtig bezwangst du die Dämonen und vollbrachtest Ramas Aufgaben.",
        "In a tiny form you appeared to Sita, in a fearsome form you burned Lanka. In a mighty form you destroyed the demons and fulfilled Rama's tasks."),
      v("6", C4, "lāya sajīvana lakhana jiyāye\nśrī raghuvīra haraṣi ura lāye\nraghupati kīnhī bahuta baṅāī\ntuma mama priya bharatahi sama bhāī",
        "Du brachtest das Lebenskraut und hast Lakshmana gerettet. Voll Freude schloss Rama dich in die Arme, lobte dich sehr und sagte: Du bist mir so lieb wie mein Bruder Bharata.",
        "You brought the life-giving herb and revived Lakshmana. Rama embraced you with joy, praised you greatly and said: you are as dear to me as my brother Bharata."),
      v("7", C4, "sahasa badana tumharo jasa gāvai\nasa kahi śrīpati kanta lagāvai\nsanakādika brahmādi munīsā\nnārada sārada sahita ahīsā",
        "„Die tausendköpfige Schlange singt deinen Ruhm“, sprach Rama und umarmte dich. Sanaka und die Weisen, Brahma und die Götter, Narada, Sarasvati und der Schlangenkönig preisen dich.",
        "\"The thousand-headed serpent sings your glory,\" said Rama and embraced you. Sanaka and the sages, Brahma and the gods, Narada, Sarasvati and the serpent king praise you."),
      v("8", C4, "yama kubera digapāla jahām̐ te\nkavi kobida kahi sake kahām̐ te\ntuma upakāra sugrīvahiṁ kīnhā\nrāma milāya rāja pada dīnhā",
        "Selbst Yama, Kubera und die Hüter der Himmelsrichtungen können deinen Ruhm nicht ganz sagen, wie dann Dichter und Gelehrte. Du halfst Sugriva, führtest ihn zu Rama und gabst ihm sein Königreich.",
        "Even Yama, Kubera and the guardians of the directions cannot fully tell your glory, how then could poets and scholars. You helped Sugriva, brought him to Rama and gave him his kingdom."),
      v("9", C4, "tumharo mantra vibhīṣaṇa mānā\nlankeśvara bhaye saba jaga jānā\nyuga sahasra yojana para bhānu\nlīlyo tāhi madhura phala jānu",
        "Vibhishana folgte deinem Rat und wurde König von Lanka, das weiß die ganze Welt. Die ferne Sonne hieltst du für eine süße Frucht und hast sie verschluckt.",
        "Vibhishana followed your counsel and became king of Lanka, as the whole world knows. The distant sun you took for a sweet fruit and swallowed it."),
      v("10", C4, "prabhu mudrikā meli mukha māhīṁ\njaladhi lāṅghi gaye acaraja nāhīṁ\ndurgama kāja jagata ke jete\nsugama anugraha tumhare tete",
        "Mit dem Ring des Herrn im Mund sprangst du über das Meer, kein Wunder bei dir. Alle schweren Aufgaben der Welt werden durch deine Gnade leicht.",
        "With the Lord's ring in your mouth you leapt across the ocean, no wonder for you. All the hard tasks of the world become easy by your grace."),
      v("11", C4, "rāma du(v)āre tuma rakhavāre\nhota na ājñā binu paisāre\nsaba sukha lahai tumhārī śaranā\ntuma rakṣaka kāhū ko ḍaranā",
        "Du hütest Ramas Tor, ohne deine Erlaubnis kommt niemand hinein. Wer bei dir Zuflucht nimmt, findet alles Glück. Mit dir als Beschützer gibt es nichts zu fürchten.",
        "You guard Rama's door, no one enters without your leave. Whoever takes refuge in you finds every joy. With you as protector there is nothing to fear."),
      v("12", C4, "āpana teja samhāro āpai\ntīnon loka hānka ten kāṁpai\nbhūta pisāca nikaṭa nahiṁ āvai\nmahāvīra jaba nāma sunāvai",
        "Nur du selbst kannst deine Kraft bändigen, bei deinem Ruf erzittern die drei Welten. Geister und böse Wesen kommen nicht nahe, wo dein Name, großer Held, erklingt.",
        "Only you can contain your own power, at your roar the three worlds tremble. Ghosts and evil spirits come nowhere near when your name, great hero, is sounded."),
      v("13", C4, "nāsai roga hare saba pīrā\njapata nirantara hanumata vīrā\nsaṁkaṭa teṁ hanumāna chuṅāvai\nmana krama bacana dhyāna jo lāvai",
        "Krankheit vergeht und aller Schmerz schwindet, wenn man ohne Unterlass deinen Namen wiederholt, tapferer Hanuman. Wer dich mit Herz, Tat und Wort betrachtet, den befreist du aus der Not.",
        "Disease ends and all pain goes when one repeats your name without pause, brave Hanuman. Whoever meditates on you in mind, deed and word, you free from distress."),
      v("14", C4, "saba para rāma tapasvī rājā\ntina ke kāja sakala tuma sājā\naura manoratha jo koī lāvai\nsoī amita jīvana phala pāvai",
        "Rama, der asketische König, steht über allem, und all seine Aufgaben hast du erfüllt. Wer mit einem Herzenswunsch zu dir kommt, erhält die grenzenlose Frucht des Lebens.",
        "Rama, the ascetic king, is above all, and you fulfilled all his tasks. Whoever comes to you with a wish receives the boundless fruit of life."),
      v("15", C4, "cāron yuga paratāpa tumhārā\nhai parasidha jagata ujiyārā\nsādhu santa ke tuma rakhavāre\nasura nikandana rāma dulāre",
        "Dein Glanz reicht durch alle vier Zeitalter und erhellt die ganze Welt. Du schützt die Heiligen und Weisen, vernichtest die Dämonen und bist Ramas Liebling.",
        "Your glory spans all four ages and lights up the whole world. You protect saints and sages, destroy the demons and are Rama's beloved."),
      v("16", C4, "aṣṭa siddhi nava nidhi ke dātā\nasa vara dīna jānakī mātā\nrāma rasāyana tumhare pāsā\nsadā raho raghupati ke dāsā",
        "Mutter Sita gab dir den Segen, die acht Kräfte und neun Schätze zu verschenken. Das Elixier des Rama-Namens ist bei dir, für immer bist du Ramas Diener.",
        "Mother Sita blessed you to bestow the eight powers and nine treasures. The elixir of Rama's name is with you, forever you remain Rama's servant."),
      v("17", C4, "tumhare bhajana rāma ko pāvai\njanama janama ke duḥkha bisarāvai\nanta kāla raghuvara pura jā-ī\njahām̐ janama hari bhakta kahā-ī",
        "Wer dich besingt, findet Rama und vergisst das Leid vieler Leben. Am Ende geht er in Ramas Reich und wird dort, wo er geboren wird, ein Geweihter Haris genannt.",
        "Whoever sings of you finds Rama and forgets the sorrow of many lives. At the end he goes to Rama's abode, and wherever he is born he is called a devotee of Hari."),
      v("18", C4, "aura devatā citta na dhara-ī\nhanumata sehī sarva sukha kara-ī\nsankaṭa kaṭe miṭe saba pīrā\njo sumire hanumata bala vīrā",
        "Auch wer an keinen anderen Gott denkt, findet durch Hanuman alles Glück. Not und Schmerz vergehen für jeden, der an den starken, tapferen Hanuman denkt.",
        "Even without thinking of any other god, one gains all happiness through Hanuman. Troubles end and all pain fades for whoever remembers the strong and brave Hanuman."),
      v("19", C4, "jai jai jai hanumāna gosāṁ-ī\nkṛpā karahu guru deva kī nāṁ-ī\njo sata bāra pāṭa kara koī\nchūṭa-ī bandi mahā sukha hoī",
        "Sieg, Sieg, Sieg dir, Herr Hanuman, sei mir gnädig wie mein Guru. Wer dies hundertmal singt, wird aus allen Fesseln befreit und findet großes Glück.",
        "Victory, victory, victory to you, Lord Hanuman, be gracious to me like my Guru. Whoever recites this a hundred times is freed from bondage and finds great joy."),
      v("20", C4, "jo yaha paḍhai hanumāna calīsā\nhoya siddhi sākhī gaurīsā\ntulasi dāsa sadā hari cerā\nkī jai nātha hṛdaya mam̐ ha ḍerā",
        "Wer diese Hanuman Chalisa liest, erlangt Vollendung, dafür bürgt Shiva. Tulasidas, für immer Diener Haris, bittet: Herr, wohne in meinem Herzen.",
        "Whoever reads this Hanuman Chalisa attains perfection, Shiva is the witness. Tulasidas, forever Hari's servant, prays: Lord, make your home in my heart."),
      v("Dohā", C4, "pavana-tanaya saṅkaṭa harana\nmaṅgala mūrati rūpa\nrāma lakhana sītā sahita\nhṛdaya basahu sura bhūpa",
        "Sohn des Windes, der alle Not nimmt, Gestalt des Segens: Wohne mit Rama, Lakshmana und Sita in meinem Herzen, König der Götter.",
        "Son of the wind, remover of troubles, embodiment of blessing: dwell in my heart together with Rama, Lakshmana and Sita, king of the gods."),
      { nr:"Kīrtan 1", ch:"D     C     G     D", sa:"śrī rām jai rām jai jai rām\nśrī rām jai rām jai jai rām", ue:"Sieg dem heiligen Rama.", en:"Victory to holy Rama.", x2:true },
      { nr:"Kīrtan 2", ch:"D     C     G     D", sa:"sītārām sītārām sītārām sītārām\nsītārām sītārām sītārām sītārām", ue:"Sita und Rama.", en:"Sita and Rama.", x2:true },
      v("Jai", "D     A     D", "siyā vara rāmacandra kī... jai!\numā vara śambhonātha kī... jai!\npavana putra hanumāna kī... jai!\nbolo bhai sab santhon kī... jai!",
        "Sieg Ramachandra, dem Gemahl Sitas! Sieg Shiva, dem Gemahl Umas! Sieg Hanuman, dem Sohn des Windes! Sieg allen Heiligen!",
        "Victory to Ramachandra, Sita's beloved! Victory to Shiva, Uma's beloved! Victory to Hanuman, son of the wind! Victory to all the saints!")
    ]
  });
})();
