/* [Grok.com] Vollstaendiges Shri Nrisimha Kavacham, 30 Slokas + Mantra */
(function(){
  var k = PRAYERS.find(function(p){ return p.id==="kavacham"; });
  if(!k) return;
  var L = "Dm   Bb    C     Dm";
  function v(n, sa, ue, en){
    return { nr: String(n), ch: L, sa: sa, ue: ue, en: en };
  }
  k.quelle = "Brahmanda Purana · Prahlada · Heft S. 20–21";
  k.hinweis = "Vollstaendiges Kavacham. Jede Strophe endet wie im Heft am zweiten Pada.";
  k.hinweisDe = "Vollstaendiges Kavacham, 30 Strophen. Zeilenumbruch wie im Original.";
  k.hinweisEn = "Complete Kavacham, 30 verses. Line break as in the original couplet.";
  k.zeilen = [
    v(1, "nṛsiṃha-kavacaṃ vakṣye prahlādenoditaṃ purā |\nsarva-rakṣākaraṃ puṇyaṃ sarvopadrava-nāśanam", "Ich spreche das Narasimha-Kavacham, einst von Prahlada gesagt. Es schützt ganz und löscht jedes Unglück.", "I recite the Narasimha Kavacham spoken by Prahlada. It protects wholly and destroys every distress."),
    v(2, "sarva-sampat-karaṃ caiva svarga-mokṣa-pradāyakam |\ndhyātvā nṛsiṃhaṃ deveśaṃ hema-siṃhāsana-sthitam", "Es bringt allen Wohlstand, Himmel und Befreiung. Man sinne auf Nrisimha auf goldenem Löwenthron.", "It gives all prosperity, heaven and liberation. Meditate on Nrisimha seated on a golden lion-throne."),
    v(3, "vivṛtāsyaṃ tri-nayanaṃ śarad-indu-sama-prabham |\nlakṣmyāliṅgita-vāmāṅgaṃ vibhūtibhir upāśritam", "Offener Mund, drei Augen, Glanz wie der Herbstmond. Lakshmi umarmt seine linke Seite.", "Open mouth, three eyes, glow like the autumn moon. Lakshmi embraces his left side."),
    v(4, "catur-bhujaṃ komalāṅgaṃ svarṇa-kuṇḍala-śobhitam |\nsaroja-śobhitoraskaṃ ratna-keyūra-mudritam", "Vier Arme, zarter Leib, goldene Ohrringe. Brust wie ein Lotus, Armreifen aus Juwelen.", "Four arms, tender body, golden earrings. Lotus-chest, jewel armlets."),
    v(5, "tapta-kāñcana-saṅkāśaṃ pīta-nirmala-vāsasam |\nindrādi-sura-mauli-stha-sphuran-māṇikya-dīptibhiḥ", "Wie geschmolzenes Gold, reines gelbes Gewand. Glanz der Rubine auf den Kronen der Götter.", "Like molten gold, a spotless yellow cloth. Ruby-light on the crowns of the gods."),
    v(6, "virājita-pada-dvandvaṃ śaṅkha-cakrādi-hetibhiḥ |\ngarutmatā savinayaṃ stūyamānaṃ mudānvitam", "Leuchtende Füße, Muschel und Diskus. Garuda preist ihn demütig und froh.", "Shining feet, conch and discus. Garuda praises him with joy and reverence."),
    v(7, "sva-hṛt-kamala-saṃvāsaṃ kṛtvā tu kavacaṃ paṭhet |\nnṛsiṃho me śiraḥ pātu loka-rakṣārtha-sambhavaḥ", "Ihn im Herzlotus wohnen lassen — dann lese man das Kavacham. Nrisimha schütze mein Haupt.", "Place him in the heart-lotus, then recite the Kavacham. May Nrisimha protect my head."),
    v(8, "sarvago 'pi stambha-vāsaḥ phālaṃ me rakṣatu dhvanim |\nnṛsiṃho me dṛśau pātu soma-sūryāgni-locanaḥ", "Der im Pfeiler wohnte schütze Stirn und Stimme. Nrisimha schütze meine Augen — Mond, Sonne, Feuer.", "He who dwelt in the pillar protect brow and voice. May Nrisimha protect my eyes — moon, sun and fire."),
    v(9, "smṛtiṃ me pātu nṛharir muni-varya-stuti-priyaḥ |\nnāsāṃ me siṃha-nāsas tu mukhaṃ lakṣmī-mukha-priyaḥ", "Nrihari schütze mein Gedächtnis. Löwennase schütze die Nase, Lakshmis Lieber das Gesicht.", "May Nrihari protect my memory. Lion-nose protect my nose, dear to Lakshmi my face."),
    v(10, "sarva-vidyādhipaḥ pātu nṛsiṃho rasanāṃ mama |\nvaktraṃ pātv indu-vadanaḥ sadā prahlāda-vanditaḥ", "Herr allen Wissens schütze meine Zunge. Mondgesicht, von Prahlada verehrt, schütze den Mund.", "Lord of all knowledge protect my tongue. Moon-faced, praised by Prahlada, protect my mouth."),
    v(11, "nṛsiṃhaḥ pātu me kaṇṭhaṃ\nskandhau bhū-bhṛd ananta\nkṛt divyāstra śobhita bhujaḥ\nnṛsiṃhaḥ pātu me bhujaḥ", "Nrisimha schütze meinen Hals. Der Bergträger, der Unendliche, mit göttlicher Waffe geschmücktem Arm schütze meine Arme.", "May Nrisimha protect my throat. The mountain-bearer, the Endless, arms adorned with divine weapons, protect my arms."),
    v(12, "karau me deva-varado nṛsiṃhaḥ pātu sarvataḥ |\nhṛdayaṃ yogi-sādhyaś ca nivāsaṃ pātu me hariḥ", "Der Wunschgewährer schütze die Hände von allen Seiten. Hari schütze Herz und Wohnsitz.", "The boon-giver protect my hands from every side. May Hari protect heart and dwelling."),
    v(13, "madhyaṃ pātu hiraṇyākṣa-vakṣaḥ-kukṣi-vidāraṇaḥ |\nnābhiṃ me pātu nṛhariḥ sva-nābhi-brahma-saṃstutaḥ", "Der Hiranyakshas Brust zeriss schütze die Mitte. Nrihari schütze den Nabel.", "He who tore Hiranyaksha protect my midriff. May Nrihari protect my navel."),
    v(14, "brahmāṇḍa-koṭayaḥ kaṭyāṃ yasyāsau pātu me kaṭim |\nguhyaṃ me pātu guhyānāṃ mantrāṇāṃ guhya-rūpa-dhṛk", "Auf dessen Hüfte Welten ruhen — schütze meine Hüfte. Der verborgene Herr schütze das Verborgene.", "He on whose hips the universes rest protect my hips. The hidden Lord protect what is hidden."),
    v(15, "ūrū manobhavaḥ pātu jānunī nara-rūpa-dhṛk |\njaṅghe pātu dharā-bhāra-hartā yo 'sau nṛ-kesarī", "Der Ur-Kama schütze die Schenkel. Menschenform schütze die Knie, der Menschenlöwe die Waden.", "The first Kama protect my thighs. Human form protect my knees, the man-lion my calves."),
    v(16, "sura-rājya-pradaḥ pātu pādau me nṛharīśvaraḥ |\nsahasra-śīrṣā puruṣaḥ pātu me sarvaśas tanum", "Der Himmelreiche gibt schütze die Füße. Der Tausendköpfige schütze den ganzen Leib.", "Giver of heavenly realms protect my feet. The thousand-headed One protect the whole body."),
    v(17, "mahograḥ pūrvataḥ pātu mahā-vīrāgrajo 'gnitaḥ |\nmahā-viṣṇur dakṣiṇe tu mahā-jvālas tu nairṛtau", "Der Furchtbare im Osten, der große Held im Südosten. Maha-Vishnu im Süden, die große Flamme im Südwesten.", "The fierce One in the east, the great hero in the south-east. Maha-Vishnu in the south, the great flame in the south-west."),
    v(18, "paścime pātu sarveśo diśi me sarvato-mukhaḥ |\nnṛsiṃhaḥ pātu vāyavyāṃ saumyāṃ bhūṣaṇa-vigrahaḥ", "Im Westen der Allherr, nach allen Seiten der Allgesichtige. Nordwest und Norden der geschmückte Nrisimha.", "In the west the Lord of all, facing every side. Northwest and north the adorned Nrisimha."),
    v(19, "īśānyāṃ pātu bhadro me sarva-maṅgala-dāyakaḥ |\nsaṃsāra-bhayataḥ pātu mṛtyor mṛtyur nṛ-kesarī", "Nordosten der Heilsame, Geber allen Segens. Vor der Angst des Werdens der Tod des Todes, der Menschenlöwe.", "Northeast the auspicious giver of all good. From the fear of becoming, the death of death, the man-lion."),
    v(20, "idaṃ nṛsiṃha-kavacaṃ prahlāda-mukha-maṇḍitam |\nbhaktimān yaḥ paṭhen nityaṃ sarva-pāpaiḥ pramucyate", "Dies Kavacham aus Prahladas Mund. Wer es täglich ergeben liest, wird von allen Sünden gelöst.", "This Kavacham adorned by Prahlada's mouth. Who reads it daily with devotion is freed from all sins."),
    v(21, "putravān dhanavān loke dīrghāyur upajāyate |\nyaṃ yaṃ kāmayate kāmaṃ taṃ taṃ prāpnoty asaṃśayam", "Kinder, Reichtum und langes Leben. Was man wünscht, das kommt ohne Zweifel.", "Children, wealth and long life. Whatever one desires, that comes without doubt."),
    v(22, "sarvatra jayam āpnoti sarvatra vijayī bhavet |\nbhūmy-antarikṣa-divyānāṃ grahāṇāṃ vinivāraṇam", "Überall Sieg. Es wehrt irdische, luftige und himmlische Planeten ab.", "Victory everywhere. It turns aside earthly, mid-air and heavenly planets."),
    v(23, "vṛścikoraga-sambhūta-viṣāpaharaṇaṃ param |\nbrahma-rākṣasa-yakṣāṇāṃ dūrotsāraṇa-kāraṇam", "Höchstes Mittel gegen Gift von Skorpion und Schlange. Es vertreibt Brahmarakshasas und Yakshas.", "Supreme remover of scorpion and snake poison. It drives Brahma-rakshasas and Yakshas far away."),
    v(24, "bhūrje vā tāla-patre vā kavacaṃ likhitaṃ śubham |\nkara-mūle dhṛtaṃ yena sidhyeyuḥ karma-siddhayaḥ", "Auf Birkenrinde oder Palmblatt geschrieben und in der Hand getragen gelingt das Werk.", "Written on birch or palm-leaf and held in the hand, works succeed."),
    v(25, "devāsura-manuṣyeṣu svaṃ svam eva jayaṃ labhet |\neka-sandhyaṃ tri-sandhyaṃ vā yaḥ paṭhen niyato naraḥ", "Unter Göttern, Asuras und Menschen siegt man. Wer es einmal oder dreimal am Tag liest.", "Among gods, asuras and humans one gains one's victory. Who reads it once or three times a day."),
    v(26, "sarva-maṅgala-māṅgalyaṃ bhuktiṃ muktiṃ ca vindati |\ndvā-triṃśati-sahasrāṇi paṭec chuddhātmanāṃ nṛṇām", "Allen Segen, Genuss und Befreiung. Zweiunddreißigtausend Lesungen reiner Menschen.", "All auspiciousness, enjoyment and liberation. Thirty-two thousand recitations of the pure."),
    v(27, "kavacasyāsya mantrasya mantra-siddhiḥ prajāyate |\nanena mantra-rājena kṛtvā bhasmābhimantraṇam", "Durch dieses Königsmantra reift die Mantra-Siddhi. Asche damit weihen.", "By this king of mantras mantra-siddhi arises. Consecrate ash with it."),
    v(28, "tilakaṃ vinyased yas tu tasya graha-bhayaṃ haret |\ntri-vāraṃ japamānas tu dattaṃ vāry abhimantrya ca", "Tilaka damit genommen nimmt die Planetenangst. Dreimal sprechen und Wasser weihen.", "A tilaka so placed removes fear of planets. Recite three times and consecrate water."),
    v(29, "prāśayed yo naro mantraṃ nṛsiṃha-dhyānam ācaret |\ntasya rogāḥ praṇaśyanti ye ca syuḥ kukṣi-sambhavāḥ", "Wer das Mantra nimmt und Nrisimha meditiert — Krankheiten, auch aus dem Bauch, weichen.", "Who takes the mantra and meditates on Nrisimha — diseases, even of the belly, perish."),
    v(30, "kim atra bahunoktena nṛsiṃha-sadṛśo bhavet |\nmanasā cintitaṃ yat tu sa tac cāpnoty asaṃśayam", "Was weiter sagen? Man wird Nrisimha gleich. Was der Geist denkt, das kommt ohne Zweifel.", "Why say more? One becomes like Nrisimha. What the mind thinks, that comes without doubt."),
    { nr:"Iti", ch:L, sa:"iti śrī-brahmāṇḍa-purāṇe prahlādoktaṃ\nśrī-nṛsiṃha-kavacam sampūrṇam", ue:"So endet im Brahmanda-Purana das von Prahlada gesprochene Shri-Nrisimha-Kavacham.", en:"Thus ends in the Brahmanda Purana the Shri Nrisimha Kavacham spoken by Prahlada." },
    { nr:"Mantra", ch:"Dm              C", sa:"oṃ namo bhagavate narasiṃhāya", ue:"Om, Verehrung dem Herrn Narasimha.", en:"Om, obeisance to Lord Narasimha." },
    { nr:"Ugram", ch:L, sa:"ugraṃ vīraṃ mahā-viṣṇuṃ jvalantaṃ sarvato mukham |\nnṛsiṃhaṃ bhīṣaṇaṃ bhadraṃ mṛtyor mṛtyuṃ namāmy aham", ue:"Den Furchtbaren, den Helden, den großen Vishnu, allseits lodernd. Nrisimha, schrecklich und heilsam, Tod des Todes — ich verneige mich.", en:"The fierce, the hero, great Vishnu, blazing on all sides. Nrisimha, terrible and auspicious, death of death — I bow." },
    { nr:"Jaya", ch:"Bb          F     C           F", sa:"jaya nṛśiṅga dev\nnṛśiṅga dev nṛśiṅga dev jaya nṛśiṅga dev ://", ue:"Sieg Narasimha Deva.", en:"Victory, Narasimha Deva." }
  ];
})();
