/* [Grok.com] Vollstaendiges Shri Nrisimha Kavacham, 31 Slokas vierzeilig wie Heft. Am Ende das Nrsimha-Gebet von Heft Seite 12, vierzeilig, nicht nur im eigenen Eintrag. */
(function(){
  var k = PRAYERS.find(function(p){ return p.id==="kavacham"; });
  if(!k) return;
  var L = "Dm   Bb    C     Dm";
  function v(n, sa, ue, en){
    return { nr: String(n), ch: L, sa: sa, ue: ue, en: en };
  }
  /* [Grok-Bot] V1.65: Lyrics (sa) und englische Übersetzung (en) aller 30 Verse und des Iti aus SNKS 1–3 (Buch S. 41–43); Vers „kim atra bahunoktena“ steht nicht in der Vorlage und entfällt; Vers 31 (garjantaṁ) ist jetzt Vers 30 */
  /* [Grok-Bot] V1.64: Titel korrigiert, Vers 11 „ananta-kṛt“ in einer Zeile */
  k.titel = "Śrī Nṛsiṁha Kavaca Stotram";
  k.quelle = "Prathana with chords · Sri Vitthal Dham · S. 20–21 · Text und Übersetzung: SNKS 1–3 (S. 41–43)";
  k.hinweis = "Strophen vierzeilig wie im Musikerheft. Am Ende das Nrsimha-Gebet von Heft Seite 12.";
  k.hinweisDe = "Jede Strophe in vier Heft-Zeilen. Am Ende das Nrsimha-Gebet, Seite 12.";
  k.hinweisEn = "Each verse in four booklet lines. The Nrsimha prayer from page 12 follows at the end.";
  k.zeilen = [
    v(1, "nṛsiṁha kavacam vakṣye\nprahlādenoditaṁ purā\nsarva rakṣa karaṁ puṇyaṁ\nsarvopadrava nāśanam", "Ich spreche das Narasimha-Kavacham, einst von Prahlada gesagt. Es schützt ganz und löscht jedes Unglück.", "I shall now recite the Nrsimha-kavacha, formerly spoken by Prahlada Maharaja. It is most pious, vanquishes all kinds of impediments, and provides one all protection."),
    v(2, "sarva sampat karaṁ caiva\nsvarga mokṣa pradāyakam\ndhyātvā nṛsiṁhaṁ deveśaṁ\nhema siṁhāsana sthitam", "Es bringt allen Wohlstand, Himmel und Befreiung.", "It bestows upon one all opulences and can give one elevation to the heavenly planets or liberation. One should meditate on Lord Nrsimha, Lord of the universe, seated upon a golden throne."),
    v(3, "vivritāsyaṁ trinayanaṁ\nśarad indu sama prabham\nlakṣmyāliṅgita vāmāṅgam\nvibhūtibhi rupāśritam", "Offener Mund, drei Augen, Lakshmi an der linken Seite.", "His mouth is wide open, He has three eyes, and He is as radiant as the autumn moon. He is embraced by Lakshmi Devi on His left side, and His form is the shelter of all opulences, both material and spiritual."),
    v(4, "catur bhujaṁ komalāṅgaṁ\nsvarṇa kuṇḍala śobhitam\nsaroja śobitoraskaṁ\nratna keyūra mudritam", "Vier Arme, goldene Ohrringe, Juwelen-Armreifen.", "The Lord has four arms and His limbs are very soft. He is decorated with golden earrings. His chest is resplendent like the lotus flower, and His arms are decorated with jewel-studded ornaments."),
    v(5, "tapta kāñcana saṅkāśaṁ\npīta nirmala vāsasam\nindrādi sura mauliṣṭhaḥ\nsphuran māṇikya dīptibhiḥ", "Wie geschmolzenes Gold, reines gelbes Gewand.", "He is dressed in a spotless yellow garment, which exactly resembles molten gold. He is the original cause of existence, beyond the mundane sphere, for the great demigods headed by Indra. He appears bedecked with rubies which are blazingly effulgent."),
    v(6, "virājita pada dvandvaṁ\nśaṅkha cakrādi hetibhiḥ\ngarutmatā ca vinayāt\nstūyamānaṁ mudānvitam", "Leuchtende Füße. Garuda preist ihn.", "His two feet are very attractive, and He is armed with various weapons such as the conch and disc. Garuda joyfully offers Him prayers with great reverence."),
    v(7, "sva hṛt kamala saṁ-vāsaṁ\nkṛtvā tu kavacaṁ paṭhet\nnṛsiṁho me śiraḥ pātu\nloka rakṣārtha sambhavaḥ", "Ihn im Herzlotus wohnen lassen, dann das Kavacham lesen.", "Having seated Lord Nrsimhadeva upon the lotus of one's heart, one should recite the following mantra: May Lord Narasimha, who protects all the planetary systems, protect my head."),
    v(8, "sarvago 'pi stambha vāsaḥ\nphalaṁ me rakṣatu dhvanim\nnṛsiṁho me dṛśau pātu\nsoma sūryāgni locanaḥ", "Der im Pfeiler wohnte schütze Stirn, Stimme und Augen.", "Although the Lord is all-pervading, He hid Himself within a pillar. May He protect my speech and the results of my activities. May Lord Nrsimha, whose eyes are the sun and fire, protect my eyes."),
    v(9, "smṛtaṁ me pātu nṛhariḥ\nmuni vārya stuti priyaḥ\nnāsaṁ me siṁha nāśas-tu\nmukhaṁ lakṣmī mukhaṁ priyaḥ", "Nrihari schütze Gedächtnis, Nase und Gesicht.", "May Lord Hari, who is pleased by the prayers offered by the best of sages, protect my memory. May He who has the nose of a lion protect my nose, and may He whose face is very dear to the Goddess of fortune protect my mouth."),
    v(10, "sarva vidyādhipaḥ pātu\nnṛsiṁho rasanaṁ mama\nvaktraṁ pātvindu vadanaṁ\nsadā prahlāda vanditaḥ", "Herr allen Wissens schütze Zunge und Mund.", "May Lord Nrsimha, who is the knower of all sciences, protect my sense of taste. May He whose face is beautiful as the full moon and who is offered prayers by Prahlada Maharaja protect my face."),
    v(11, "nṛsiṁhaḥ pātu me kaṇṭhaṁ\nskandhau bhū-bhṛd ananta kṛt\ndivyāstra śobhita bhujaḥ\nnṛsiṁhaḥ pātu me bhujau", "Nrisimha schütze Hals und Arme.", "May Lord Nrsimhadeva protect my throat. He is the sustainer of the earth and the performer of unlimited wonderful activities. May He protect my shoulders. His arms are resplendent with transcendental weapons. May He protect my shoulders."),
    v(12, "karau me deva varado\nnṛsiṁhaḥ pātu sarvataḥ\nhṛdayaṁ yogi sādhyaś ca\nnivāsaṁ pātu me hariḥ", "Der Wunschgewährer schütze Hände, Herz und Wohnsitz.", "May the Lord, who bestows benedictions upon the demigods, protect my hands, and may He protect me from all sides. May He who is achieved by the perfect yogis protect my heart, and may Lord Hari protect my dwelling place."),
    v(13, "madhyaṁ pātu hiraṇyākṣa\nvakṣaḥ kukṣi vidāraṇaḥ\nnābhiṁ me pātu nṛhariḥ\nsva nābhi brahma saṁstutaḥ", "Er schütze Mitte und Nabel.", "May He who ripped apart the chest and abdomen of the great demon Hiranyakashipu protect my waist, and may Lord Hari protect my navel. He is offered prayers by Lord Brahma, who has sprung from His own navel."),
    v(14, "brahmāṇḍa koṭayaḥ kaṭyāṁ\nyasyāsau pātu me kaṭim\nguhyaṁ me pātu guhyānāṁ\nmantrāṇāṁ guhya rūpa dṛk", "Er schütze Hüfte und das Verborgene.", "May He on whose hips rest all the universes protect my hips. May the Lord protect my private parts. He is the knower of all mantras and all mysteries, but He Himself is not visible."),
    v(15, "ūrū manobhavaḥ pātu\njānunī nara rūpa dṛk\njaṅghe pātu dharā bhara\nhartā yo 'sau nṛkeśarī", "Schenkel, Knie und Waden schütze der Menschenlöwe.", "May He who is the original cupid protect my thighs. May He who exhibits a human-like form protect my knees. May the remover of the burden of the earth, who appears in a form which is half-man and half-lion, protect my calves."),
    v(16, "sura rājya pradaḥ pātu\npādau me nṛharīśvaraḥ\nsahasra śīrṣā puruṣaḥ\npātu me sarva-śas-tanum", "Füße und den ganzen Leib schütze er.", "May the bestower of heavenly opulence protect my feet. He is the Supreme Controller in the form of a man and lion combined. May the thousand-headed Supreme enjoyer protect my body from all sides and in all respects."),
    v(17, "mahograḥ pūrvataḥ pātu\nmahā virāgrajo 'gnitaḥ\nmahā viṣṇur dakṣiṇe tu\nmahā jvalas tu nairṛtaḥ", "Osten, Südosten, Süden, Südwesten.", "May that most ferocious personality protect me from the east. May He who is superior to the greatest heroes protect me from the southeast, which is presided over by Agni. May the Supreme Vishnu protect me from the south, and may that person of blazing lustre protect me from the southwest."),
    v(18, "paścime pātu sarveśo\ndiśi me sarvatomukhaḥ\nnṛsiṁhaḥ pātu vāyavyāṁ\nsaumyāṁ bhūṣaṇa vigrahaḥ", "Westen, alle Seiten, Nordwest, Norden.", "May the Lord of everything protect me from the west. His faces are everywhere, so please may He protect me from this direction. May Lord Narasimha protect me from the northwest, which is predominated by Vayu, and may He whose form is in itself the Supreme ornament protect me from the north, where Soma resides."),
    v(19, "īśānyāṁ pātu bhadro me\nsarva maṅgala dayakaḥ\nsaṁsāra bhayataḥ pātu\nmṛtyor mṛtyur nṛkeśari", "Nordosten der Heilsame. Der Tod des Todes schütze.", "May the all-auspicious Lord, who Himself bestows all-auspiciousness, protect from the northeast, the direction of the Sun-God, and may He who is death personified protect me from fear of death and rotation in this material world."),
    v(20, "idaṁ nṛsiṁha kavacaṁ\nprahlāda mukha maṇḍitam\nbhaktimān yaḥ paṭhennityaṁ\nsarva pāpaiḥ pramucyate", "Wer es täglich ergeben liest, wird von Sünden gelöst.", "This Narasimha-kavacha has been ornamented by issuing from the mouth of Prahlada Maharaja. A devotee who reads this becomes freed from all sins."),
    v(21, "putravān dhanavān loke\ndīrghāyur upajāyate\nkāmayate yaṁ yaṁ kāmaṁ\ntam taṁ prāpnoty asaṁśayam", "Was man in dieser Welt wünscht, erlangt man ohne Zweifel: Reichtum, viele Söhne und ein langes Leben.", "Whatever one desires in this world he can attain without doubt. One can have wealth, many sons and a long life."),
    v(22, "sarvatra jayam āpnoti\nsarvatra vijayī bhavet\nbhūmy antarīkṣa divyānāṁ\ngrahāṇām vini vāraṇam", "Überall Sieg. Es wehrt die Planeten ab.", "He becomes victorious, who desires victory, and indeed becomes a conqueror. He wards off the influence of all planets, earthly, heavenly and everything in between."),
    v(23, "vṛś-cikoraga sambhūta\nviṣāpaharaṇaṁ param\nbrahma rākṣasa yakṣāṇāṁ\ndūrotsāraṇa kāraṇam", "Gegen Gift und Yakshas.", "This is the supreme remedy for the poisonous effects of serpents and scorpions, Brahma-rakshasa ghosts and Yakshas are driven away."),
    v(24, "bhuje vā tāla pātre vā\nkavacaṁ likhitaṁ śubham\nkara mūle dhṛtaṁ yena\nsidhyeyuḥ karma siddhayaḥ", "Auf den Arm oder ein Palmblatt geschrieben und am Handgelenk getragen, gelingt jedes Werk.", "One may write this most auspicious prayer on his arm, or inscribe it on a palm-leaf and attach it to his wrist and all his activities will become perfect."),
    v(25, "devāsura manuṣyeṣu\nsvaṁ svaṁ eva jayaṁ labhet\neka sandhyaṁ tri sandhyaṁ vā\nyaḥ paṭhen-niyato naraḥ", "Wer es einmal oder dreimal am Tag liest, siegt.", "One who regularly chants this prayer, whether once or thrice (daily), becomes victorious whether among demigods, demons or human beings."),
    v(26, "sarva maṅgala maṅgalyaṁ\nbhuktiṁ muktiṁ ca vindati\ndvā triṁ-śati sahasrāṇi\npaṭhet śuddhātmanām nṛṇām", "Segen, Genuss und Befreiung.", "One who with purified heart recites this prayer 32,000 times attains the most auspicious of all auspicious things, and material enjoyment and liberation are already understood to be available to such a person."),
    v(27, "kavacasyāsya mantrasya\nmantra siddhiḥ prajāyate\nanena mantra rājena\nkṛtvā bhasmābhir mantrāṇām", "Durch dieses Königsmantra reift die Siddhi.", "This Kavacha-mantra is the king of all mantras. One attains by it what would be attained by anointing oneself with ashes and chanting all other mantras."),
    v(28, "tilakaṁ vinyased yas tu\ntasya graha bhayaṁ haret\ntri vāraṁ japa-mānas tu\ndattaṁ vāryābhi-mantrya ca", "Tilaka und geweihtes Wasser nehmen die Planetenangst.", "Having marked ones body with tilaka, taking acamana with water, and reciting this mantra three times, one will find that the fear of all inauspicious planets is removed."),
    v(29, "prasayed yo naro mantraṁ\nnṛsiṁha dhyānam ācaret\ntasya rogāḥ prana-śyanti\nye ca syuḥ kukṣi sambhavāḥ", "Wer meditiert — Krankheiten weichen.", "That person who recites this mantra, meditating upon Lord Nrsimhadeva, has all of his diseases vanquished, including those of the abdomen."),
    v(30, "garjantaṁ gārjayantaṁ\nnija bhuja paṭalam\nsphoṭayantaṁ haṭhantaṁ\nrūpyantaṁ tāpayantam\ndivi bhuvi ditijaṁ\nkṣepa-yantaṁ kṣipantam\nkrandantaṁ roṣa-yantaṁ\ndiśi diśi satantaṁ\nsaṁ-harantaṁ bharantaṁ\nvīkṣantaṁ pūrṇayantaṁ\nkara nikara śatair\ndivya siṁhaṁ namāmi", "Dem göttlichen Löwen, der brüllt und brüllen lässt, seine Arme ausbreitet, die Dämonen am Himmel und auf Erden schlägt, peinigt und fortschleudert, in alle Richtungen zürnt, vernichtet und erhält, mit hunderten Händen erfüllt und überschaut, bringe ich meine Verehrung dar.", "Lord Nrsimha roars loudly and causes others to roar. With His multitudes of arms He tears the demons asunder and kills them in this way. He is always seeking out and tormenting the demoniac descendants of Diti, both on this earth planet and in the higher planets, and He throws them down and scatters them. He cries with great anger as He destroys the demons in all directions, yet with His unlimited hands He sustains, protects, and nourishes the cosmic manifestation. I offer my respectful obeisances to the Lord, who has assumed the form of a transcendental lion."),
    { nr:"Iti", ch:L, sa:"iti śrī brāhmāṇḍa purāṇe\nprahlādoktam\nśrī nṛsiṁha kavacaṁ\nsampūrṇam sampūrṇam", ue:"So endet das von Prahlada gesprochene Kavacham.", en:"Thus ends the Nrsimha-kavacha as it is described by Prahlada Maharaja in the Brahmana Purana." },
    { nr:"Mantra", ch:"Dm              C", sa:"oṃ namo bhagavate\nnarasiṃhāya", ue:"Om, Verehrung dem Herrn Narasimha.", en:"Om, obeisance to Lord Narasimha." },
    { nr:"Ugram", ch:L, sa:"ugraṃ vīraṃ mahā-viṣṇuṃ\njvalantaṃ sarvato mukham\nnṛsiṃhaṃ bhīṣaṇaṃ bhadraṃ\nmṛtyor mṛtyuṃ namāmy aham", ue:"Den Furchtbaren, den Helden — ich verneige mich.", en:"The fierce, the hero — I bow." },
    { nr:"Jaya", ch:"Bb          F     C           F", sa:"jaya nṛśiṅga dev\nnṛśiṅga dev nṛśiṅga dev\njaya nṛśiṅga dev ://", ue:"Sieg Narasimha Deva.", en:"Victory, Narasimha Deva." },
    /* [Grok.com] Heft Seite 12, nach dem Kavacam gesungen. Vier Zeilen je Strophe, eigener Eintrag bleibt. */
    { nr:"Namaste", ch:"Dm   Bb    C     Dm", sa:"namaste nārasiṁhāya\nprahlādāh-lāda dāyine\nhiraṇyākaśipur vakṣaḥ\nśilā taṅka nakhālāye", ue:"Verehrung dir, Narasimha, der du Prahlada Freude schenkst. Deine Nägel, wie Meißel, spalteten die Brust des Hiranyakashipu.", en:"Obeisance to Narasimha, who gives joy to Prahlada. Your nails, like chisels, split the chest of Hiranyakashipu." },
    { nr:"Ito", ch:"Dm   Bb    C     Dm", sa:"ito nṛsiṁho parato nṛsiṁho\nyato yato yāmi tato nṛsiṁho\nbahir nṛsiṁho hṛdaye nṛsiṁho\nnṛsiṁham ādiṁ śaranam prapadye", ue:"Hier Narasimha, dort Narasimha. Wohin ich gehe, dort Narasimha. Außen Narasimha, im Herzen Narasimha. Bei Narasimha, dem Ursprung, suche ich Zuflucht.", en:"Narasimha here, Narasimha there. Wherever I go, there is Narasimha. Outside Narasimha, in the heart Narasimha. In Narasimha, the origin, I take refuge." },
    { nr:"Tava", ch:"Dm    F    C    Dm", sa:"tava kara kamala vare\nnakhām adbhuta śriṅgāṁ\ndalitā hiraṇyakaśipu\ntanu bhṛṅgam", ue:"An deiner Lotoshand die wundersame Nagelspitze, die den Leib des Hiranyakashipu wie eine Wespe zerbrach.", en:"On your lotus hand the wondrous nail-point, which tore the body of Hiranyakashipu like a wasp." },
    { nr:"Keshava", ch:"Dm    F    C    Bb", sa:"keśava dhṛta nara hari rūpa\njaya jagadīśa hare\njaya jagadīśa hare\njaya jagadīśa hare", ue:"Keshava, der die Gestalt von Mensch und Löwe annahm. Sieg, Herr der Welt, Hari.", en:"Keshava who took the form of man and lion. Victory, Lord of the world, Hari." }
  ];
})();
/* [Grok-Bot] V1.65: Versionsanzeige (nach listview.js). */
document.addEventListener("DOMContentLoaded", function(){ setTimeout(function(){ var v=document.querySelector("h1 .ver"); if(v) v.textContent="V1.65"; document.title="Bhakti Prayers Player V1.65"; }, 30); });
