/* [Grok-Bot] V1.67: Espanol (es) fuer kavacham, narasimha-abend, narasimha, aus der englischen Prathana-Uebersetzung (Zuordnung ueber window.bppNrEn aus tr-fr.js). */
(function(){
if(!window.bppNrTr) return;
window.bppNrTr("es",[
"Ahora recitaré el Nrisimha-kavacha, pronunciado antiguamente por Prahlada Maharaja. Es sumamente sagrado, vence toda clase de impedimentos y otorga protección completa.",
"Concede todas las riquezas y puede elevar a los planetas celestiales o a la liberación. Se debe meditar en el Señor Nrisimha, Señor del universo, sentado en un trono de oro.",
"Su boca está muy abierta, tiene tres ojos y es tan radiante como la luna de otoño. Lakshmi Devi lo abraza por Su lado izquierdo, y Su forma es el refugio de todas las riquezas, tanto materiales como espirituales.",
"El Señor tiene cuatro brazos y Sus miembros son muy suaves. Está adornado con pendientes de oro. Su pecho resplandece como la flor de loto, y Sus brazos están adornados con joyas engastadas de piedras preciosas.",
"Viste una prenda amarilla inmaculada, idéntica al oro fundido. Él es la causa original de la existencia, más allá de la esfera mundana, para los grandes semidioses encabezados por Indra. Aparece engalanado con rubíes de brillo deslumbrante.",
"Sus dos pies son muy atractivos, y está armado con diversas armas, como la caracola y el disco. Garuda le ofrece oraciones con alegría y gran reverencia.",
"Tras haber sentado al Señor Nrisimhadeva sobre el loto del propio corazón, se debe recitar el siguiente mantra: Que el Señor Narasimha, que protege todos los sistemas planetarios, proteja mi cabeza.",
"Aunque el Señor lo impregna todo, se ocultó dentro de un pilar. Que Él proteja mi habla y los frutos de mis actos. Que el Señor Nrisimha, cuyos ojos son el sol y el fuego, proteja mis ojos.",
"Que el Señor Hari, a quien complacen las oraciones de los mejores sabios, proteja mi memoria. Que Aquel que tiene nariz de león proteja mi nariz, y que Aquel cuyo rostro es muy querido por la diosa de la fortuna proteja mi boca.",
"Que el Señor Nrisimha, conocedor de todas las ciencias, proteja mi sentido del gusto. Que Aquel cuyo rostro es hermoso como la luna llena y a quien Prahlada Maharaja ofrece oraciones proteja mi rostro.",
"Que el Señor Nrisimhadeva proteja mi garganta. Él es el sustentador de la tierra y el autor de innumerables actividades maravillosas. Que Él proteja mis hombros. Sus brazos resplandecen con armas trascendentales. Que Él proteja mis hombros.",
"Que el Señor, que concede bendiciones a los semidioses, proteja mis manos, y que me proteja por todos lados. Que Aquel a quien alcanzan los yoguis perfectos proteja mi corazón, y que el Señor Hari proteja mi morada.",
"Que Aquel que desgarró el pecho y el abdomen del gran demonio Hiranyakashipu proteja mi cintura, y que el Señor Hari proteja mi ombligo. A Él ofrece oraciones el Señor Brahma, que surgió de Su propio ombligo.",
"Que Aquel sobre cuyas caderas descansan todos los universos proteja mis caderas. Que el Señor proteja mis partes íntimas. Él conoce todos los mantras y todos los misterios, pero Él mismo no es visible.",
"Que Aquel que es el Cupido original proteja mis muslos. Que Aquel que muestra una forma semejante a la humana proteja mis rodillas. Que quien quita la carga de la tierra y aparece en una forma mitad hombre y mitad león proteja mis pantorrillas.",
"Que el otorgador de la opulencia celestial proteja mis pies. Él es el Controlador Supremo en la forma combinada de hombre y león. Que el Supremo disfrutador de mil cabezas proteja mi cuerpo por todos lados y en todos los aspectos.",
"Que esa personalidad ferocísima me proteja desde el este. Que Aquel que supera a los más grandes héroes me proteja desde el sureste, que preside Agni. Que el Supremo Vishnu me proteja desde el sur, y que esa persona de brillo resplandeciente me proteja desde el suroeste.",
"Que el Señor de todo me proteja desde el oeste. Sus rostros están en todas partes; que Él, por favor, me proteja desde esta dirección. Que el Señor Narasimha me proteja desde el noroeste, regido por Vayu, y que Aquel cuya forma es en sí misma el adorno supremo me proteja desde el norte, donde reside Soma.",
"Que el Señor todo auspicioso, que Él mismo otorga toda auspiciosidad, me proteja desde el noreste, la dirección del dios del Sol, y que Aquel que es la muerte personificada me proteja del temor a la muerte y de la rotación en este mundo material.",
"Este Narasimha-kavacha está adornado por haber brotado de la boca de Prahlada Maharaja. El devoto que lo lee queda libre de todos los pecados.",
"Todo lo que uno desee en este mundo puede obtenerlo sin duda. Uno puede tener riqueza, muchos hijos y una larga vida.",
"Quien desea la victoria se vuelve victorioso y llega a ser realmente un conquistador. Aleja la influencia de todos los planetas, terrenales, celestiales y de todo lo que hay entre ellos.",
"Este es el remedio supremo contra los efectos venenosos de serpientes y escorpiones; los fantasmas brahma-rakshasa y los yakshas son ahuyentados.",
"Uno puede escribir esta oración sumamente auspiciosa en su brazo, o inscribirla en una hoja de palma y atarla a su muñeca, y todas sus actividades se volverán perfectas.",
"Quien canta regularmente esta oración, ya sea una o tres veces (al día), sale victorioso, ya sea entre semidioses, demonios o seres humanos.",
"Quien, con el corazón purificado, recita esta oración 32 000 veces alcanza lo más auspicioso de todas las cosas auspiciosas, y se entiende que el disfrute material y la liberación ya están al alcance de esa persona.",
"Este mantra del kavacha es el rey de todos los mantras. Por medio de él se obtiene lo que se obtendría ungiéndose con cenizas y cantando todos los demás mantras.",
"Tras marcar el propio cuerpo con tilaka, hacer achamana con agua y recitar este mantra tres veces, uno verá que el temor a todos los planetas desfavorables desaparece.",
"La persona que recita este mantra meditando en el Señor Nrisimhadeva ve vencidas todas sus enfermedades, incluidas las del abdomen.",
"El Señor Nrisimha ruge con fuerza y hace rugir a los demás. Con Sus multitudes de brazos despedaza a los demonios y así los mata. Siempre está buscando y atormentando a los descendientes demoníacos de Diti, tanto en este planeta Tierra como en los planetas superiores, y los derriba y los dispersa. Grita con gran ira mientras destruye a los demonios en todas las direcciones; sin embargo, con Sus manos ilimitadas sustenta, protege y nutre la manifestación cósmica. Ofrezco mis respetuosas reverencias al Señor, que ha adoptado la forma de un león trascendental.",
"Así termina el Nrisimha-kavacha tal como lo describe Prahlada Maharaja en el Brahmanda Purana.",
"Te ofrezco mis respetuosas reverencias, Señor Nrisimhadeva. Tú das alegría a Prahlada, y Tus uñas cortaron el pecho de Hiranyakashipu como un cincel que corta la piedra.",
"El Señor Nrisimha está aquí y también allá. Dondequiera que voy, allí está el Señor Nrisimha. Está en el corazón y también fuera. Me entrego al Señor Nrisimha, el origen de todas las cosas y el refugio supremo.",
"Así como uno puede aplastar fácilmente una avispa entre las uñas, del mismo modo el cuerpo del demonio Hiranyakashipu, semejante a una avispa, fue desgarrado por las maravillosas uñas puntiagudas de Tus hermosas manos de loto.",
"¡Oh, Keshava! ¡Oh, Señor del universo! ¡Oh, Señor Hari, que has adoptado la forma mitad hombre y mitad león! ¡Toda gloria a Ti!",
"Ofrezco mis respetuosas reverencias al Señor Nrisimhadeva, la fuente de todo poder. Oh, mi Señor, que posees uñas y dientes como rayos, vence por favor nuestros deseos demoníacos de actividades fruitivas en este mundo material.",
"Por favor, aparece en nuestros corazones y disipa nuestra ignorancia, para que por Tu misericordia nos volvamos intrépidos en la lucha por la existencia en este mundo material.",
"Oh, Señor Nrisimha, que apareciste con manos como armas y con un cuerpo dorado y resplandeciente, Tú estás aquí para destruir todos los pecados por siempre jamás.",
"Tienes dientes y uñas como rayos, y estás coronado por una melena de llamas.",
"Cortando, partiendo, desgarrando y matando, protégenos, por favor, a nosotros, Tus devotos, y cumple nuestro deseo de servirte.",
"¡Reverencias al Señor Nrisimhadeva, que arde y llamea con Su propia refulgencia abrasadora, cuyos ojos derraman torrentes de fuego vivo, igualados solo por el brillo de Sus dientes relucientes, y que destruye a todos los fantasmas y rakshasas!",
"¡Reverencias al destructor de todos los demonios, al exterminador de todos los fantasmas, al vencedor de toda clase de fiebres! ¡Oh, mi Señor! ¡Quema, quema a mis enemigos, cuécelos, cuécelos a todos! ¡Por favor, Señor Nrisimhadeva, presérvame, presérvame y protégeme!",
"Mis reverencias al feroz y poderoso, el gran Vishnu, el ardiente cuyos rostros están en todos los lados, el temible, Nrisimha, que causa la muerte incluso a la muerte personificada, o que puede vencer incluso a la muerte.",
"Meditemos en Aquel que posee uñas tan duras como rayos y dientes afilados. Que el Señor Nrisimha nos inspire.",
"Que el Señor Nrisimhadeva, que apareció como enemigo de Hiranyakashipu, me proteja en todas las direcciones. Su fuerte risa vibró en todas las direcciones e hizo abortar a las esposas embarazadas de los asuras. Que ese Señor tenga la bondad de protegerme en lugares difíciles como el bosque y el campo de batalla.",
"Prahlada Maharaja cantó en voz alta el santo nombre del Señor Nrisimhadeva. Que el Señor Nrisimhadeva, que ruge por Su devoto Prahlada Maharaja, nos proteja de todo temor a los peligros creados por poderosos caudillos en todas las direcciones mediante veneno, armas, agua, fuego, aire, etc. Que el Señor cubra su influencia con Su propia influencia trascendental. Que Nrisimhadeva nos proteja en todas las direcciones y en todos los rincones, arriba, abajo, dentro y fuera.",
"Oh, mi Señor, oh, león trascendental, Te ofrezco mis reverencias junto con Madre Lakshmi. A veces volando por el cielo, a veces caminando a pie, los pelos de Tu melena arden con un brillo dorado. Tu mirada y el toque de Tus uñas son la fuente de toda auspiciosidad.",
"¡Victoria a Ti, Hari! ¡Victoria a Lakshmi-Nrisimhadeva!",
"Victoria a Nrisimhadeva",
"¡Victoria a Nrisimhadeva, Bhakta Prahlada! ¡Victoria a la encarnación de la bhakti: Bhakta Prahlada Maharaja!",
"¡Victoria a Gurudeva! ¡Victoria a Gurudeva Sri Swami Vishwananda!",
"¡Victoria a Gurudeva!"
]);
})();
