/* [Grok-Bot] V1.67: Nrsimha-Uebersetzungen aus der englischen Prathana-Uebersetzung (Ausgangstext).
   Gilt fuer kavacham (51 Strophen), narasimha-abend (lange Fassung) und narasimha (kurze Fassung morgens).
   window.bppNrEn = die 52 englischen Ausgangstexte; zugeordnet wird ueber den Text in z.en.
   Diese Datei setzt DE (Feld ue, vollstaendige Uebersetzung statt Kurzfassung) und FR (Feld fr).
   ES/RU/HI folgen in tr-es.js, tr-ru.js, tr-hi.js. Die ue-Texte in kavacham.js/tr-en.js werden hier ueberschrieben. */
(function(){
window.bppNrEn=[
"I shall now recite the Nrsimha-kavacha, formerly spoken by Prahlada Maharaja. It is most pious, vanquishes all kinds of impediments, and provides one all protection.",
"It bestows upon one all opulences and can give one elevation to the heavenly planets or liberation. One should meditate on Lord Nrsimha, Lord of the universe, seated upon a golden throne.",
"His mouth is wide open, He has three eyes, and He is as radiant as the autumn moon. He is embraced by Lakshmi Devi on His left side, and His form is the shelter of all opulences, both material and spiritual.",
"The Lord has four arms and His limbs are very soft. He is decorated with golden earrings. His chest is resplendent like the lotus flower, and His arms are decorated with jewel-studded ornaments.",
"He is dressed in a spotless yellow garment, which exactly resembles molten gold. He is the original cause of existence, beyond the mundane sphere, for the great demigods headed by Indra. He appears bedecked with rubies which are blazingly effulgent.",
"His two feet are very attractive, and He is armed with various weapons such as the conch and disc. Garuda joyfully offers Him prayers with great reverence.",
"Having seated Lord Nrsimhadeva upon the lotus of one's heart, one should recite the following mantra: May Lord Narasimha, who protects all the planetary systems, protect my head.",
"Although the Lord is all-pervading, He hid Himself within a pillar. May He protect my speech and the results of my activities. May Lord Nrsimha, whose eyes are the sun and fire, protect my eyes.",
"May Lord Hari, who is pleased by the prayers offered by the best of sages, protect my memory. May He who has the nose of a lion protect my nose, and may He whose face is very dear to the Goddess of fortune protect my mouth.",
"May Lord Nrsimha, who is the knower of all sciences, protect my sense of taste. May He whose face is beautiful as the full moon and who is offered prayers by Prahlada Maharaja protect my face.",
"May Lord Nrsimhadeva protect my throat. He is the sustainer of the earth and the performer of unlimited wonderful activities. May He protect my shoulders. His arms are resplendent with transcendental weapons. May He protect my shoulders.",
"May the Lord, who bestows benedictions upon the demigods, protect my hands, and may He protect me from all sides. May He who is achieved by the perfect yogis protect my heart, and may Lord Hari protect my dwelling place.",
"May He who ripped apart the chest and abdomen of the great demon Hiranyakashipu protect my waist, and may Lord Hari protect my navel. He is offered prayers by Lord Brahma, who has sprung from His own navel.",
"May He on whose hips rest all the universes protect my hips. May the Lord protect my private parts. He is the knower of all mantras and all mysteries, but He Himself is not visible.",
"May He who is the original cupid protect my thighs. May He who exhibits a human-like form protect my knees. May the remover of the burden of the earth, who appears in a form which is half-man and half-lion, protect my calves.",
"May the bestower of heavenly opulence protect my feet. He is the Supreme Controller in the form of a man and lion combined. May the thousand-headed Supreme enjoyer protect my body from all sides and in all respects.",
"May that most ferocious personality protect me from the east. May He who is superior to the greatest heroes protect me from the southeast, which is presided over by Agni. May the Supreme Vishnu protect me from the south, and may that person of blazing lustre protect me from the southwest.",
"May the Lord of everything protect me from the west. His faces are everywhere, so please may He protect me from this direction. May Lord Narasimha protect me from the northwest, which is predominated by Vayu, and may He whose form is in itself the Supreme ornament protect me from the north, where Soma resides.",
"May the all-auspicious Lord, who Himself bestows all-auspiciousness, protect from the northeast, the direction of the Sun-God, and may He who is death personified protect me from fear of death and rotation in this material world.",
"This Narasimha-kavacha has been ornamented by issuing from the mouth of Prahlada Maharaja. A devotee who reads this becomes freed from all sins.",
"Whatever one desires in this world he can attain without doubt. One can have wealth, many sons and a long life.",
"He becomes victorious, who desires victory, and indeed becomes a conqueror. He wards off the influence of all planets, earthly, heavenly and everything in between.",
"This is the supreme remedy for the poisonous effects of serpents and scorpions, Brahma-rakshasa ghosts and Yakshas are driven away.",
"One may write this most auspicious prayer on his arm, or inscribe it on a palm-leaf and attach it to his wrist and all his activities will become perfect.",
"One who regularly chants this prayer, whether once or thrice (daily), becomes victorious whether among demigods, demons or human beings.",
"One who with purified heart recites this prayer 32,000 times attains the most auspicious of all auspicious things, and material enjoyment and liberation are already understood to be available to such a person.",
"This Kavacha-mantra is the king of all mantras. One attains by it what would be attained by anointing oneself with ashes and chanting all other mantras.",
"Having marked ones body with tilaka, taking acamana with water, and reciting this mantra three times, one will find that the fear of all inauspicious planets is removed.",
"That person who recites this mantra, meditating upon Lord Nrsimhadeva, has all of his diseases vanquished, including those of the abdomen.",
"Lord Nrsimha roars loudly and causes others to roar. With His multitudes of arms He tears the demons asunder and kills them in this way. He is always seeking out and tormenting the demoniac descendants of Diti, both on this earth planet and in the higher planets, and He throws them down and scatters them. He cries with great anger as He destroys the demons in all directions, yet with His unlimited hands He sustains, protects, and nourishes the cosmic manifestation. I offer my respectful obeisances to the Lord, who has assumed the form of a transcendental lion.",
"Thus ends the Nrsimha-kavacha as it is described by Prahlada Maharaja in the Brahmana Purana.",
"I offer my respectful obeisances unto You Lord Nrsimhadeva. You are the giver of pleasure to Prahlada and Your nails cut the chest of Hiranyakashipu like a chisel cutting stone.",
"Lord Nrsimha is here and also there. Wherever I go Lord Nrsimha is there. He is in the heart and is in the outside as well. I surrender to Lord Nrsimha, the origin of all things and the Supreme refuge.",
"Just as one can easily crush a wasp between ones fingernails, so in the same way the body of a wasp like demon Hiryanakashipu has been ripped apart by the wonderful pointed nails on Your beautiful lotus hands.",
"Oh Keshava! Oh Lord of the Universe! Oh Lord Hari who has assumed the form of half-man half-lion. All glories to You!",
"I offer my respectful obeisances unto Lord Nrsimha Deva, the source of all power. Oh my Lord who possesses nails and teeth just like thunderbolts, kindly vanquish our demon like desires for fruitive activity in this material world.",
"Please appear in our hearts and drive away our ignorance so that by Your mercy we may become fearless in the struggle for existence in this material world.",
"Oh Lord Nrsimha, You who appeared with hands like weapon and with golden and shiny body, You are here to destroy all sins for ever and ever.",
"You have teeth and nails like bolts of lighting and are garlanded by a mane of flames.",
"Chopping, cutting, tearing and killing, please protect us Your devotees and fulfill our desire to serve You.",
"Obeisances to the Lord Nrsimhadeva, ablaze and burning with His own scorching effulgence. Whose eyes pour forth torrents of living fire, matched only by the glow of His glistening teeth, destroying all ghosts and rakshasas!",
"Obeisances to the destroyer of all demons, to the slayer of all ghosts, to the vanquisher of all types of fever! Oh my Lord! Burn and burn my enemies, cook and cook them all! Please Lord Nrsimhadeva, preserve, preserve, and protect me!",
"My obeisances unto the ferocious and powerful, the great Vishnu, the fiery one whose faces are on all sides, the fearful one, Nrsimha, who causes the death of even death personified, or who can overcome even death.",
"Let us meditate on He who is the possessor of nails as hard as thunderbolts and sharp teeth. Let us be enthused by Lord Nrsimha.",
"May Lord Nrsimhadeva, who appeared as the enemy of Hiranyakashipu, protect me in all directions. His loud laughing vibrated in all directions and caused the pregnant wives of the asuras to have miscarriages. May that Lord be kind enough to protect me in difficult places like the forest and the battlefront.",
"Prahlada Maharaj loudly chanted the holy name of Lord Nrsimhadeva. May Lord Nrsimhadeva, roaring for His devotee Prahlada Maharaj, protect us from all fear of dangers created by stalwart leaders in all directions through poison, weapons, water, fire, air and so on. May the Lord cover their influence by His own transcendental influence. May Nrsimhadeva protect us in all directions and in all corners, above, below, within and without.",
"Oh my Lord, Oh transcendental lion, I offer my obeisances unto You along with Mother Lakshmi. Sometimes flying in the sky, sometimes moving on foot, Your mane hairs blaze with a golden brilliance. Your glance and the touch of Your nails are the source of all auspiciousness.",
"Victory to You Hari! Victory to Lakshmi Nrsimhadeva!",
"Victory to Nrsimhadeva",
"Victory to Nrsimhadeva, Bhakta Prahlad! Victory to the embodiment of Bhakti: Bhakta Prahlad Maharaj.",
"Victory to Gurudeva! Victory to Gurudeva Sri Swami Vishwananda!",
"Victory to Gurudeva!"
];
window.bppNrTr=function(field,arr){
  var ids=["kavacham","narasimha-abend","narasimha"], keys=window.bppNrEn||[], n=0;
  if(typeof PRAYERS==="undefined") return 0;
  PRAYERS.forEach(function(k){ if(ids.indexOf(k.id)<0||!k.zeilen) return;
    k.zeilen.forEach(function(z){ var j=z.en?keys.indexOf(z.en):-1; if(j>=0&&arr[j]){ z[field]=arr[j]; n++; } else if(!z.en&&field!=="ue"){ z[field]=""; } }); });
  return n;
};
/* [Grok-Bot] V1.67: Deutsch (ue) aus dem Englischen */
window.bppNrTr("ue",[
"Ich werde nun das Nṛsiṁha-Kavaca vortragen, das einst Prahlāda Mahārāja sprach. Es ist höchst heilig, besiegt alle Arten von Hindernissen und gewährt vollkommenen Schutz.",
"Es schenkt alle Reichtümer und kann zu den himmlischen Planeten oder zur Befreiung erheben. Man soll über Śrī Nṛsiṁha meditieren, den Herrn des Universums, der auf einem goldenen Thron sitzt.",
"Sein Mund ist weit geöffnet, Er hat drei Augen und strahlt wie der Herbstmond. Lakṣmī Devī umarmt Ihn an Seiner linken Seite, und Seine Gestalt ist die Zuflucht aller Reichtümer, materieller wie spiritueller.",
"Der Herr hat vier Arme, und Seine Glieder sind sehr zart. Er ist mit goldenen Ohrringen geschmückt. Seine Brust glänzt wie eine Lotosblume, und Seine Arme sind mit juwelenbesetztem Schmuck verziert.",
"Er trägt ein makelloses gelbes Gewand, das genau wie geschmolzenes Gold aussieht. Für die großen Halbgötter mit Indra an der Spitze ist Er die ursprüngliche Ursache des Daseins, jenseits der weltlichen Sphäre. Er erscheint geschmückt mit Rubinen, die gleißend leuchten.",
"Seine beiden Füße sind sehr anziehend, und Er ist mit verschiedenen Waffen wie Muschelhorn und Diskus bewaffnet. Garuḍa bringt Ihm voller Freude und mit großer Ehrfurcht Gebete dar.",
"Hat man Śrī Nṛsiṁhadeva auf dem Lotos seines Herzens Platz nehmen lassen, soll man das folgende Mantra sprechen: Möge Śrī Narasiṁha, der alle Planetensysteme beschützt, mein Haupt beschützen.",
"Obwohl der Herr alldurchdringend ist, verbarg Er sich in einer Säule. Möge Er meine Rede und die Früchte meines Handelns beschützen. Möge Śrī Nṛsiṁha, dessen Augen Sonne und Feuer sind, meine Augen beschützen.",
"Möge Śrī Hari, den die Gebete der besten Weisen erfreuen, mein Gedächtnis beschützen. Möge Er, der die Nase eines Löwen hat, meine Nase beschützen, und möge Er, dessen Antlitz der Göttin des Glücks sehr lieb ist, meinen Mund beschützen.",
"Möge Śrī Nṛsiṁha, der Kenner aller Wissenschaften, meinen Geschmackssinn beschützen. Möge Er, dessen Antlitz schön ist wie der Vollmond und dem Prahlāda Mahārāja Gebete darbringt, mein Gesicht beschützen.",
"Möge Śrī Nṛsiṁhadeva meine Kehle beschützen. Er ist der Erhalter der Erde und der Vollbringer unbegrenzter wunderbarer Taten. Möge Er meine Schultern beschützen. Seine Arme glänzen mit transzendentalen Waffen. Möge Er meine Schultern beschützen.",
"Möge der Herr, der den Halbgöttern Segen gewährt, meine Hände beschützen, und möge Er mich von allen Seiten beschützen. Möge Er, den die vollkommenen Yogīs erreichen, mein Herz beschützen, und möge Śrī Hari meinen Wohnort beschützen.",
"Möge Er, der Brust und Bauch des großen Dämons Hiraṇyakaśipu zerriss, meine Taille beschützen, und möge Śrī Hari meinen Nabel beschützen. Ihm bringt Śrī Brahmā Gebete dar, der aus Seinem eigenen Nabel hervorgegangen ist.",
"Möge Er, auf dessen Hüften alle Universen ruhen, meine Hüften beschützen. Möge der Herr meine Geschlechtsteile beschützen. Er ist der Kenner aller Mantras und aller Geheimnisse, doch Er selbst ist nicht sichtbar.",
"Möge Er, der der ursprüngliche Liebesgott ist, meine Oberschenkel beschützen. Möge Er, der eine menschenähnliche Gestalt zeigt, meine Knie beschützen. Möge Er, der die Last der Erde fortnimmt und in einer Gestalt halb Mensch, halb Löwe erscheint, meine Waden beschützen.",
"Möge der Spender himmlischen Reichtums meine Füße beschützen. Er ist der Höchste Herrscher in der vereinten Gestalt von Mensch und Löwe. Möge der tausendköpfige Höchste Genießer meinen Körper von allen Seiten und in jeder Hinsicht beschützen.",
"Möge jene überaus grimmige Persönlichkeit mich vom Osten her beschützen. Möge Er, der die größten Helden übertrifft, mich vom Südosten her beschützen, über den Agni waltet. Möge der Höchste Viṣṇu mich vom Süden her beschützen, und möge jene Person von lodernder Strahlkraft mich vom Südwesten her beschützen.",
"Möge der Herr von allem mich vom Westen her beschützen. Seine Gesichter sind überall; so möge Er mich bitte aus dieser Richtung beschützen. Möge Śrī Narasiṁha mich vom Nordwesten her beschützen, über den Vāyu waltet, und möge Er, dessen Gestalt selbst der höchste Schmuck ist, mich vom Norden her beschützen, wo Soma weilt.",
"Möge der allglückverheißende Herr, der selbst alles Glück schenkt, mich vom Nordosten her beschützen, der Richtung des Sonnengottes, und möge Er, der der personifizierte Tod ist, mich vor der Angst vor dem Tod und vor dem Kreislauf in dieser materiellen Welt beschützen.",
"Dieses Narasiṁha-Kavaca ist geschmückt, weil es aus dem Mund Prahlāda Mahārājas hervorging. Ein Gottgeweihter, der es liest, wird von allen Sünden frei.",
"Was immer man in dieser Welt wünscht, kann man ohne Zweifel erlangen. Man kann Reichtum, viele Söhne und ein langes Leben haben.",
"Wer den Sieg wünscht, wird siegreich und wahrhaft zum Eroberer. Er wehrt den Einfluss aller Planeten ab, der irdischen, der himmlischen und aller dazwischen.",
"Dies ist das höchste Heilmittel gegen die giftigen Wirkungen von Schlangen und Skorpionen; Brahma-Rākṣasa-Geister und Yakṣas werden vertrieben.",
"Man kann dieses höchst glückverheißende Gebet auf seinen Arm schreiben oder es auf ein Palmblatt ritzen und an seinem Handgelenk befestigen, und all seine Unternehmungen werden vollkommen.",
"Wer dieses Gebet regelmäßig singt, ob einmal oder dreimal (täglich), wird siegreich, ob unter Halbgöttern, Dämonen oder Menschen.",
"Wer dieses Gebet mit gereinigtem Herzen 32.000 Mal rezitiert, erlangt das Glückverheißendste aller glückverheißenden Dinge, und man weiß, dass materieller Genuss und Befreiung einem solchen Menschen bereits zur Verfügung stehen.",
"Dieses Kavaca-Mantra ist der König aller Mantras. Durch es erlangt man, was man erlangen würde, wenn man sich mit Asche salbte und alle anderen Mantras chantete.",
"Wer seinen Körper mit Tilaka gezeichnet, mit Wasser Ācamana vollzogen und dieses Mantra dreimal rezitiert hat, wird erleben, dass die Furcht vor allen unheilvollen Planeten beseitigt ist.",
"Wer dieses Mantra rezitiert und dabei über Śrī Nṛsiṁhadeva meditiert, dem werden alle Krankheiten besiegt, auch die des Unterleibs.",
"Śrī Nṛsiṁha brüllt laut und lässt andere brüllen. Mit Seinen vielen Armen reißt Er die Dämonen auseinander und tötet sie auf diese Weise. Stets spürt Er die dämonischen Nachkommen Ditis auf und peinigt sie, sowohl auf diesem Erdplaneten als auch auf den höheren Planeten, und Er wirft sie nieder und zerstreut sie. Er schreit vor großem Zorn, während Er die Dämonen in allen Richtungen vernichtet, und doch erhält, beschützt und nährt Er mit Seinen unbegrenzten Händen die kosmische Schöpfung. Ich bringe dem Herrn, der die Gestalt eines transzendentalen Löwen angenommen hat, meine achtungsvollen Ehrerbietungen dar.",
"So endet das Nṛsiṁha-Kavaca, wie es von Prahlāda Mahārāja im Brahmāṇḍa Purāṇa beschrieben wird.",
"Ich bringe Dir, Śrī Nṛsiṁhadeva, meine achtungsvollen Ehrerbietungen dar. Du schenkst Prahlāda Freude, und Deine Nägel zerschnitten die Brust Hiraṇyakaśipus wie ein Meißel, der Stein schneidet.",
"Śrī Nṛsiṁha ist hier und auch dort. Wohin ich auch gehe, ist Śrī Nṛsiṁha. Er ist im Herzen und ebenso außen. Ich ergebe mich Śrī Nṛsiṁha, dem Ursprung aller Dinge und der höchsten Zuflucht.",
"So wie man eine Wespe leicht zwischen den Fingernägeln zerdrücken kann, so wurde der Körper des wespengleichen Dämons Hiraṇyakaśipu von den wunderbaren spitzen Nägeln an Deinen schönen Lotoshänden zerrissen.",
"O Keśava! O Herr des Universums! O Śrī Hari, der Du die Gestalt halb Mensch, halb Löwe angenommen hast! Alle Ehre sei Dir!",
"Ich bringe Śrī Nṛsiṁhadeva, der Quelle aller Kraft, meine achtungsvollen Ehrerbietungen dar. O mein Herr, der Du Nägel und Zähne wie Donnerkeile besitzt, besiege bitte unsere dämonischen Wünsche nach fruchtbringendem Handeln in dieser materiellen Welt.",
"Bitte erscheine in unseren Herzen und vertreibe unsere Unwissenheit, damit wir durch Deine Barmherzigkeit im Kampf ums Dasein in dieser materiellen Welt furchtlos werden.",
"O Śrī Nṛsiṁha, der Du mit Händen wie Waffen und mit goldenem, leuchtendem Körper erschienen bist, Du bist hier, um alle Sünden für immer und ewig zu vernichten.",
"Du hast Zähne und Nägel wie Blitze und bist von einer Mähne aus Flammen umkränzt.",
"Hackend, schneidend, reißend und tötend – bitte beschütze uns, Deine Gottgeweihten, und erfülle unseren Wunsch, Dir zu dienen.",
"Ehrerbietungen Śrī Nṛsiṁhadeva, der lodert und brennt in Seiner eigenen sengenden Ausstrahlung. Seine Augen ergießen Ströme lebendigen Feuers, denen nur das Glühen Seiner glänzenden Zähne gleichkommt, und Er vernichtet alle Geister und Rākṣasas!",
"Ehrerbietungen dem Vernichter aller Dämonen, dem Bezwinger aller Geister, dem Besieger aller Arten von Fieber! O mein Herr! Verbrenne, verbrenne meine Feinde, koche sie alle, koche sie! Bitte, Śrī Nṛsiṁhadeva, bewahre, bewahre und beschütze mich!",
"Meine Ehrerbietungen dem grimmigen und mächtigen, dem großen Viṣṇu, dem Feurigen, dessen Gesichter nach allen Seiten blicken, dem Furchterregenden, Nṛsiṁha, der selbst dem personifizierten Tod den Tod bringt, der sogar den Tod überwinden kann.",
"Lasst uns über Ihn meditieren, der Nägel so hart wie Donnerkeile und scharfe Zähne besitzt. Möge Śrī Nṛsiṁha uns begeistern.",
"Möge Śrī Nṛsiṁhadeva, der als Feind Hiraṇyakaśipus erschien, mich in allen Richtungen beschützen. Sein lautes Lachen hallte in allen Richtungen wider und ließ die schwangeren Frauen der Asuras Fehlgeburten erleiden. Möge dieser Herr so gütig sein, mich an schwierigen Orten wie im Wald und auf dem Schlachtfeld zu beschützen.",
"Prahlāda Mahārāja chantete laut den heiligen Namen Śrī Nṛsiṁhadevas. Möge Śrī Nṛsiṁhadeva, der für Seinen Geweihten Prahlāda Mahārāja brüllt, uns vor aller Furcht vor Gefahren beschützen, die mächtige Anführer in allen Richtungen durch Gift, Waffen, Wasser, Feuer, Luft und so weiter verursachen. Möge der Herr ihren Einfluss mit Seinem eigenen transzendentalen Einfluss bedecken. Möge Nṛsiṁhadeva uns in allen Richtungen und in allen Winkeln beschützen, oben, unten, innen und außen.",
"O mein Herr, o transzendentaler Löwe, ich bringe Dir zusammen mit Mutter Lakṣmī meine Ehrerbietungen dar. Bald fliegst Du am Himmel, bald gehst Du zu Fuß, und die Haare Deiner Mähne lodern in goldenem Glanz. Dein Blick und die Berührung Deiner Nägel sind die Quelle allen Glücks.",
"Sieg Dir, Hari! Sieg Lakṣmī-Nṛsiṁhadeva!",
"Sieg Nṛsiṁhadeva",
"Sieg Nṛsiṁhadeva, Bhakta Prahlāda! Sieg der Verkörperung der Bhakti: Bhakta Prahlāda Mahārāja.",
"Sieg Gurudeva! Sieg Gurudeva Śrī Swami Vishwananda!",
"Sieg Gurudeva!"
]);
/* [Grok-Bot] V1.67: Francais (fr) aus dem Englischen */
window.bppNrTr("fr",[
"Je vais maintenant réciter le Nrisimha-kavacha, autrefois prononcé par Prahlada Maharaja. Il est des plus saints, il vainc toutes sortes d'obstacles et procure une protection complète.",
"Il accorde toutes les richesses et peut élever jusqu'aux planètes célestes ou à la libération. On doit méditer sur le Seigneur Nrisimha, Seigneur de l'univers, assis sur un trône d'or.",
"Sa bouche est grande ouverte, Il a trois yeux et Il rayonne comme la lune d'automne. Lakshmi Devi L'enlace à Son côté gauche, et Sa forme est le refuge de toutes les richesses, matérielles comme spirituelles.",
"Le Seigneur a quatre bras et Ses membres sont très délicats. Il est paré de boucles d'oreilles en or. Sa poitrine resplendit comme la fleur de lotus, et Ses bras sont ornés de bijoux sertis de pierres précieuses.",
"Il est vêtu d'un vêtement jaune immaculé, en tout point semblable à de l'or en fusion. Il est la cause originelle de l'existence, au-delà de la sphère mondaine, pour les grands devas menés par Indra. Il apparaît paré de rubis d'un éclat flamboyant.",
"Ses deux pieds sont très attrayants, et Il porte diverses armes telles que la conque et le disque. Garouda Lui adresse joyeusement des prières avec une grande vénération.",
"Après avoir installé le Seigneur Nrisimhadeva sur le lotus de son cœur, on doit réciter le mantra suivant : Que le Seigneur Narasimha, qui protège tous les systèmes planétaires, protège ma tête.",
"Bien que le Seigneur soit omniprésent, Il s'est caché dans un pilier. Qu'Il protège ma parole et les fruits de mes actes. Que le Seigneur Nrisimha, dont les yeux sont le soleil et le feu, protège mes yeux.",
"Que le Seigneur Hari, que réjouissent les prières des meilleurs des sages, protège ma mémoire. Que Celui qui a le nez d'un lion protège mon nez, et que Celui dont le visage est très cher à la déesse de la fortune protège ma bouche.",
"Que le Seigneur Nrisimha, qui connaît toutes les sciences, protège mon sens du goût. Que Celui dont le visage est beau comme la pleine lune et à qui Prahlada Maharaja adresse ses prières protège mon visage.",
"Que le Seigneur Nrisimhadeva protège ma gorge. Il est le soutien de la terre et l'auteur d'innombrables actes merveilleux. Qu'Il protège mes épaules. Ses bras resplendissent d'armes transcendantales. Qu'Il protège mes épaules.",
"Que le Seigneur, qui accorde Ses bénédictions aux devas, protège mes mains, et qu'Il me protège de tous côtés. Que Celui qu'atteignent les yogis accomplis protège mon cœur, et que le Seigneur Hari protège ma demeure.",
"Que Celui qui déchira la poitrine et le ventre du grand démon Hiranyakashipou protège ma taille, et que le Seigneur Hari protège mon nombril. Le Seigneur Brahma, né de Son propre nombril, Lui adresse des prières.",
"Que Celui sur les hanches de qui reposent tous les univers protège mes hanches. Que le Seigneur protège mes parties intimes. Il connaît tous les mantras et tous les mystères, mais Lui-même n'est pas visible.",
"Que Celui qui est le Cupidon originel protège mes cuisses. Que Celui qui manifeste une forme semblable à celle d'un homme protège mes genoux. Que Celui qui ôte le fardeau de la terre et apparaît sous une forme mi-homme, mi-lion protège mes mollets.",
"Que le dispensateur de l'opulence céleste protège mes pieds. Il est le Maître suprême sous la forme unie d'un homme et d'un lion. Que le suprême jouisseur aux mille têtes protège mon corps de tous côtés et à tous égards.",
"Que cette personnalité des plus redoutables me protège de l'est. Que Celui qui surpasse les plus grands héros me protège du sud-est, que préside Agni. Que le Vishnou suprême me protège du sud, et que cette personne à l'éclat flamboyant me protège du sud-ouest.",
"Que le Seigneur de toutes choses me protège de l'ouest. Ses visages sont partout ; qu'Il daigne donc me protéger de cette direction. Que le Seigneur Narasimha me protège du nord-ouest, que domine Vayou, et que Celui dont la forme est en elle-même l'ornement suprême me protège du nord, où réside Soma.",
"Que le Seigneur tout de bon augure, qui accorde Lui-même tout ce qui est propice, me protège du nord-est, direction du dieu du Soleil, et que Celui qui est la mort personnifiée me protège de la peur de la mort et du cycle dans ce monde matériel.",
"Ce Narasimha-kavacha est paré d'être sorti de la bouche de Prahlada Maharaja. Le dévot qui le lit est libéré de tous ses péchés.",
"Tout ce que l'on désire en ce monde, on peut l'obtenir sans aucun doute. On peut avoir la richesse, de nombreux fils et une longue vie.",
"Celui qui désire la victoire devient victorieux et devient véritablement un conquérant. Il écarte l'influence de toutes les planètes, terrestres, célestes et de tout ce qui se trouve entre les deux.",
"C'est le remède suprême contre les effets venimeux des serpents et des scorpions ; les spectres brahma-rakshasa et les yakshas sont chassés.",
"On peut écrire cette prière des plus propices sur son bras, ou l'inscrire sur une feuille de palmier et l'attacher à son poignet, et toutes ses activités deviendront parfaites.",
"Celui qui chante régulièrement cette prière, une fois ou trois fois (par jour), devient victorieux, que ce soit parmi les devas, les démons ou les êtres humains.",
"Celui qui, le cœur purifié, récite cette prière 32 000 fois obtient ce qu'il y a de plus propice parmi toutes les choses propices, et l'on sait que la jouissance matérielle et la libération sont déjà à la portée d'une telle personne.",
"Ce mantra du kavacha est le roi de tous les mantras. On obtient par lui ce que l'on obtiendrait en s'oignant de cendres et en chantant tous les autres mantras.",
"Après avoir marqué son corps de tilaka, fait l'achamana avec de l'eau et récité ce mantra trois fois, on constatera que la crainte de toutes les planètes néfastes est écartée.",
"La personne qui récite ce mantra en méditant sur le Seigneur Nrisimhadeva voit toutes ses maladies vaincues, y compris celles de l'abdomen.",
"Le Seigneur Nrisimha rugit puissamment et fait rugir les autres. De Ses innombrables bras, Il met les démons en pièces et les tue ainsi. Sans cesse, Il traque et tourmente les descendants démoniaques de Diti, aussi bien sur cette planète Terre que sur les planètes supérieures, et Il les abat et les disperse. Il pousse des cris de grande colère tandis qu'Il détruit les démons dans toutes les directions, et pourtant, de Ses mains illimitées, Il soutient, protège et nourrit la manifestation cosmique. J'offre mes respectueux hommages au Seigneur, qui a pris la forme d'un lion transcendantal.",
"Ainsi s'achève le Nrisimha-kavacha tel que le décrit Prahlada Maharaja dans le Brahmanda Pourana.",
"Je T'offre mes respectueux hommages, Seigneur Nrisimhadeva. Tu donnes la joie à Prahlada, et Tes ongles ont fendu la poitrine d'Hiranyakashipou comme un ciseau taille la pierre.",
"Le Seigneur Nrisimha est ici et aussi là-bas. Partout où je vais, le Seigneur Nrisimha est là. Il est dans le cœur et aussi à l'extérieur. Je m'abandonne au Seigneur Nrisimha, l'origine de toutes choses et le refuge suprême.",
"De même que l'on peut aisément écraser une guêpe entre ses ongles, de même le corps du démon Hiranyakashipou, semblable à une guêpe, a été déchiré par les merveilleux ongles pointus de Tes belles mains de lotus.",
"Ô Keshava ! Ô Seigneur de l'univers ! Ô Seigneur Hari, qui as pris la forme mi-homme, mi-lion ! Gloire à Toi !",
"J'offre mes respectueux hommages au Seigneur Nrisimhadeva, la source de toute puissance. Ô mon Seigneur, Toi qui possèdes des ongles et des dents semblables à la foudre, daigne vaincre nos désirs démoniaques d'actions intéressées en ce monde matériel.",
"Daigne apparaître dans nos cœurs et chasser notre ignorance, afin que, par Ta miséricorde, nous devenions intrépides dans la lutte pour l'existence en ce monde matériel.",
"Ô Seigneur Nrisimha, Toi qui es apparu avec des mains semblables à des armes et un corps doré et resplendissant, Tu es ici pour détruire tous les péchés à tout jamais.",
"Tu as des dents et des ongles semblables à des éclairs, et Tu es couronné d'une crinière de flammes.",
"Hachant, tranchant, déchirant et tuant, protège-nous, nous Tes dévots, et exauce notre désir de Te servir.",
"Hommages au Seigneur Nrisimhadeva, embrasé et brûlant de Son propre éclat ardent, dont les yeux déversent des torrents de feu vivant, que seule égale la lueur de Ses dents étincelantes, et qui détruit tous les spectres et les rakshasas !",
"Hommages au destructeur de tous les démons, au pourfendeur de tous les spectres, au vainqueur de toutes les sortes de fièvres ! Ô mon Seigneur ! Brûle, brûle mes ennemis, consume-les, consume-les tous ! Je T'en prie, Seigneur Nrisimhadeva, préserve-moi, préserve-moi et protège-moi !",
"Mes hommages au féroce et puissant, au grand Vishnou, l'ardent dont les visages sont tournés de tous côtés, le redoutable, Nrisimha, qui donne la mort à la mort personnifiée elle-même, ou qui peut vaincre la mort même.",
"Méditons sur Celui qui possède des ongles aussi durs que la foudre et des dents acérées. Que le Seigneur Nrisimha nous inspire.",
"Que le Seigneur Nrisimhadeva, apparu comme l'ennemi d'Hiranyakashipou, me protège dans toutes les directions. Son rire tonitruant a retenti dans toutes les directions et a fait avorter les épouses enceintes des asuras. Que ce Seigneur ait la bonté de me protéger dans les lieux difficiles, comme la forêt et le champ de bataille.",
"Prahlada Maharaja chanta à voix forte le saint nom du Seigneur Nrisimhadeva. Que le Seigneur Nrisimhadeva, qui rugit pour Son dévot Prahlada Maharaja, nous protège de toute crainte des dangers créés par de puissants chefs dans toutes les directions, par le poison, les armes, l'eau, le feu, l'air, etc. Que le Seigneur recouvre leur influence de Sa propre influence transcendantale. Que Nrisimhadeva nous protège dans toutes les directions et dans tous les recoins, en haut, en bas, au-dedans et au-dehors.",
"Ô mon Seigneur, ô lion transcendantal, je T'offre mes hommages ainsi qu'à Mère Lakshmi. Tantôt volant dans le ciel, tantôt marchant à pied, les poils de Ta crinière flamboient d'un éclat doré. Ton regard et le toucher de Tes ongles sont la source de tout ce qui est propice.",
"Victoire à Toi, Hari ! Victoire à Lakshmi-Nrisimhadeva !",
"Victoire à Nrisimhadeva",
"Victoire à Nrisimhadeva, Bhakta Prahlada ! Victoire à l'incarnation de la bhakti : Bhakta Prahlada Maharaja.",
"Victoire au Gurudeva ! Victoire au Gurudeva Sri Swami Vishwananda !",
"Victoire au Gurudeva !"
]);
})();
